keys:
  - age10lpg38f5v0vwv629rmdv9859usdv8e9dr7nenlz3g5cwgy0elqgs4ae46d

creation_rules:
  - path_regex: secrets/.*\.yaml$
    key_groups:
      - age: 
          - age10lpg38f5v0vwv629rmdv9859usdv8e9dr7nenlz3g5cwgy0elqgs4ae46d
    encrypted_regex: '^(git\..*|.*)$'
